server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      static-locations: 
        - classpath:/static/
        - file:${user.dir}/upload/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mvc:
    static-path-pattern: /**
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线命名和驼峰命名的自动转换

# 文件上传相关配置
file:
  upload-path: ${user.dir}/upload/avatar

# 用户目录配置
user:
  dir: ${user.dir}
