spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线命名和驼峰命名的自动转换
